# eslint configuration file
root: true

# extending recommended configurations
extends:
  - airbnb-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - next
  - next/core-web-vitals
  - prettier

# defining the parser and environment
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
  tsconfigRootDir: .
  project: ./tsconfig.json
env:
  browser: true
  node: true

# enabling some commonly used rules
rules:
  semi: ['error', 'always']
  quotes: ['error', 'single']
  '@typescript-eslint/indent': ['error', 2]
  linebreak-style: ['error', 'unix']
  'max-len': ['error', { code: 120, tabWidth: 2, ignoreUrls: true }]
  'no-console': 'error'
  'no-unused-vars': ['error', { 'argsIgnorePattern': '^_' }]
  # configuring rules for plugins
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  'jsx-a11y/label-has-for': 'off'
  'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx', '.ts', '.tsx'] }]

# configuring plugins
plugins:
  - '@typescript-eslint'
  - 'import'
  - 'jsx-a11y'
  - 'react'
  - 'react-hooks'

# enabling some recommended plugin rules
settings:
  react:
    version: 'detect'
  'import/resolver':
    node: { extensions: ['.js', '.jsx', '.ts', '.tsx'] }